name: Add Issue To Org Project

on:
  issues:
    types:
      - opened

jobs:
  add-issue-to-project:
    uses: Evolution-Perspectives/.github/.github/workflows/add-issue-to-org-project-action.yml@main
    with:
      project_id: PVT_kwDOCIcusc4BOGrD
      issue_node_id: ${{ github.event.issue.node_id }}
      issue_number: ${{ github.event.issue.number }}
      source_repository: ${{ github.repository }}
      dry_run: false
      debug: false
    secrets:
      automation_pat: ${{ secrets.EP_AUTOMATION_PAT }}
