name: Nouvelle Page Web
description: Demande de nouvelle page web.
title: "[Nouvelle page web] "
body:
  - type: markdown
    attributes:
      value: |
        <!-- new-page-web-form:v1 -->
        Utilisez ce formulaire pour demander une nouvelle page web.

  - type: input
    id: nom-page
    attributes:
      label: Nom de la page
      placeholder: Exemple Formation Coach Pro
    validations:
      required: true
